import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import "@/styles/globals.css";
import Footer from "@/components/footer/Footer"
import Header from "@/components/header/Header"


const inter = Inter({
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Cars-Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
