import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import BootstrapClient from "@/components/bootstrap/BootstrapClient";
import "react-toastify/dist/ReactToastify.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import React from "react";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { AuthProvider } from "@/context/authContext";
import Providers from "./providers"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cars-Center",
  description: "Generated by create next app",
  icons: { icon: "/images/favicon.ico" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <BootstrapClient />
        <div className="app d-flex flex-column">
          <Header />
          <AuthProvider>
            <Providers>
              <main className="container col-12">{children}</main>
              <ToastContainer />
            </Providers>
          </AuthProvider>
          <Footer />
        </div>
      </body>
    </html>
  );
}
